### ISSUE TITLE
The strings in new2.base.php aren't localized

### ISSUE THREAD

**Issue by rpkoller** [lifeinthegrid/duplicator#10]
Nearly every localization function in new2.base.php is missing its unique identifiers. Aside that the strings which are in the files jquery part aren't localization ready either.

**Comment by lifeinthegrid** [comment]
The DUP_Util::_e method removes the need for adding the unique identifiers to every method.   This is a new methodology the plugin is going to be using going forward.   The unique id is handled by the method, which makes the method cleaner and easier to use...

**Comment by rpkoller** [comment]
ah didn't know that. cool. then the only two visible occasions are within the jquery part. "warn" and "good" aren't localized within the jquery part. those are the two occasions i've referred to in particular. it is in line 437 and 439.

**Comment by lifeinthegrid** [comment]
Yeah that is a current problem with the current code base.  Right now it keys off the string 'Warn' and 'Fail' so the logic will have to change first before it can be localized.   I will that to the todo list...
