### ISSUE TITLE
Installer File Cleanup - Fails to delete 'dup-installer-log__*' file

### ISSUE THREAD

**Issue by lucanos** [lifeinthegrid/duplicator#149]
The Installer Cleanup reports that 5 files were deleted:

> Removed - /var/www/vhosts/[My Hosting]/dup-installer
> Removed - /var/www/vhosts/[My Hosting]/installer.php
> Removed - /var/www/vhosts/[My Hosting]/installer-backup.php
> Removed - /var/www/vhosts/[My Hosting]/dup-installer-bootlog__ec6e73a-08222705.txt
> Removed - /var/www/vhosts/[My Hosting]/20190108_[My Filename]_ec6e73af60fa9d8f5071_20190108222705_archive.daf

However, the "wp-snapshots/installer/dup-installer-log__*" is not deleted or listed.

**Comment by lifeinthegrid** [comment]
Hi Luke,

We actually leave that there for support issues.   Many users will try and contact us with issues after they have run the step 4 cleanup, so we place that there for a backup history.

Thanks~

**Comment by lucanos** [comment]
Ah, OK. Wasn't aware of that. Thanks for the clarification.
