### ISSUE TITLE
Make zip link easier to copy

### ISSUE THREAD

**Issue by lordspace** [lifeinthegrid/duplicator#16]
Hi Cory,

It would be really nice if you can tweak the download buttons so they are links so I can right click and copy and not a button. Otherwise I have to go to Details > Share

![screenshot 2016-03-24 18 19 28](https://cloud.githubusercontent.com/assets/137558/14023480/36a340f6-f1ed-11e5-87dd-a9f311d732d2.png)

**Comment by lifeinthegrid** [comment]
Hey Svetoslov,

Latter in the year we hope to get to custom preferences in the Pro version, some of this could trickle down into the free version, which will allow for custom preferences has you mention...  Right now we have been working allot on stabilization across the 10 million hosting server configuration and work through a bug backlog...
