### ISSUE TITLE
Validator regex still need adjustment

### ISSUE THREAD

**Issue by ArroWsGM** [lifeinthegrid/duplicator#167]
Awesome plugin guys, thank you a LOT, but it can be even better!
I think, for file extension it should be something like this:
```
/^\.?[^\\\/*:<>?"|\s\.]+$/
```
or
```
/^\.?[^\\\/*:<>?"|\s\.]{1,255}$/
```

and for email I suggests to use recommended regular expression from [w3.org](https://www.w3.org/TR/html5/forms.html#valid-e-mail-address)

```
/^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/
```

**Comment by andreamk** [comment]
Excellent signaling.

I have updated the regexes.
in that of the file extension, I added the exclusion of the \0 char.

Thank you
Andrea
