### ISSUE TITLE
installer.php is running out of memory during explode() with large database

### ISSUE THREAD

**Issue by michael-milette** [lifeinthegrid/duplicator#17]
Good day LifeInTheGrid Team,

I am finding it impossible to use Duplicator v1.6.6 WordPress plugin to clone my site to a different server/URL. I am hoping you will be able to resolve the issue as the plugin otherwise seems to work very well.

When I run the installer.php, the following message appears instead of the process completing leaving my website with an empty database - and hence, useless:

```
Step 1: Files & Database
Please try again an issue has occurred.

server code: 0
status: error
response: undefined
```

I checked my PHP settings and have 512 MB of RAM associated with running PHP scripts and a timeout of 10 minutes. The script fails within 2-4 minutes.

Upon further investigation, the whole SQL script appears to be read into a variable. Tracing through the script using simple debug techniques, I was able to determine that it is the following line in installer.php which fails:

```
 $sql_result_file_data = explode(";\n", $sql_file);
```

There are no visible error message that I could find, even in the log.

The contents of the $sql_file variable seem to be correct so I have to assume that it my 80 MB database is causing PHP to run out of memory even though I have 512 MB available to it (as set in my php.ini). My hosting provider does not allow more than 512 MB of memory to be allocated.

I would like to proposed that the installer.php code be modified so that it only reads in one SQL statements at a time into memory instead of the whole script in one shot. I believe that the [PHP stream_get_line() function](http://php.net/manual/en/function.stream-get-line.php) can be used to achieve this in much the same way as the explode() function was parsing the whole script. The code would look something like (untested code!):

```
$handle = fopen('database.sql', 'r');
$sqlCommand = stream_get_line($handle, 1048576, ";\n"); // 1 MB maximum should be enough.
while (!feof($handle))
    If (!empty(trim($sqlCommand))) {
        // Process the line.
        // Execute the SQL query to import the data.
    }
    $sqlCommand = stream_get_line($handle, 1048576, ";\n");
}
fclose($handle);
```

This will dramatically cut down on the memory requirements. The "stream_get_line" function is pretty fast and if we don't need to keep reading and writing the SQL file, it may even result in the script taking less time to execute in addition to being less prone to memory related issues. It will even be able to handle file sizes of 1 GB though that may take a while to complete.

Let me know if you have any questions. Hopefully you can help me out.

Best regards,

Michael Milette

**Comment by lifeinthegrid** [comment]
Hi Michael,

 

Would you mind putting this into a ticket, this way I can better manage the thread.

 

https://lifeinthegrid.com/support

 

Thanks much

**Comment by michael-milette** [comment]
Hi Cory,

No problem @lifeinthegrid. Done. :-)

Best regards,

Michael
