### ISSUE TITLE
original htaccess not used?!?

### ISSUE THREAD

**Issue by lordspace** [lifeinthegrid/duplicator#178]
hey, I just migrated my blog to another host and noticed that the original .htaccess file wasn't used and duplicator generated a new one ?!? why
I had some cool redirect rules. It was just a luck that just noticed it.

**Comment by lifeinthegrid** [comment]
Hey @lordspace,

The installer has done this for quite a while.  It will create a back of the .htaccess.  If you don't want the installer to update the .htaccess then on step 1 of installer under options you can check the box to prevent the installer from messing with it.

Hope that helps~
