### ISSUE TITLE
DB Errors on Update

### ISSUE THREAD

**Issue by lucanos** [lifeinthegrid/duplicator#18]
Whenever I update Duplicator, I see a pile of DB errors immediately afterwards. They are only shown once.

> WordPress database error: [Duplicate column name 'id']
> ALTER TABLE wander_wp_duplicator_packages ADD COLUMN `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
> 
> WordPress database error: [Duplicate column name 'name']
> ALTER TABLE wander_wp_duplicator_packages ADD COLUMN `name`   VARCHAR(250)    NOT NULL
> 
> WordPress database error: [Duplicate column name 'hash']
> ALTER TABLE wander_wp_duplicator_packages ADD COLUMN `hash`   VARCHAR(50) NOT NULL
> 
> WordPress database error: [Duplicate column name 'status']
> ALTER TABLE wander_wp_duplicator_packages ADD COLUMN `status` INT(11) NOT NULL
> 
> WordPress database error: [Duplicate column name 'created']
> ALTER TABLE wander_wp_duplicator_packages ADD COLUMN `created`    DATETIME    NOT NULL DEFAULT '0000-00-00 00:00:00'
> 
> WordPress database error: [Duplicate column name 'owner']
> ALTER TABLE wander_wp_duplicator_packages ADD COLUMN `owner`  VARCHAR(60) NOT NULL
> 
> WordPress database error: [Duplicate column name 'package']
> ALTER TABLE wander_wp_duplicator_packages ADD COLUMN `package`    MEDIUMBLOB  NOT NULL
> 
> WordPress database error: [Duplicate key name 'hash']
> ALTER TABLE wander_wp_duplicator_packages ADD KEY `hash` (`hash`)

Just looks like there needs to be a check before these columns or keys are added, or at least these errors should be captured and ignored.

(Or use the WP dbDelta functionality to do same...)

**Comment by lifeinthegrid** [comment]
Hey Luke,

 

We have had random reports of that happening from time to time.   I’m not sure why I haven’t ever experienced it.   The errors are emitted from the core WP function DBDelta, the real fix needs to be applied there,   its on the to-do list.    Your welcome to help out if you want :)

**Comment by lifeinthegrid** [comment]
This looks to have been fixed in the DBDelta function have not had any reports of this in years.  Closing for now.
