### ISSUE TITLE
Code snippet to make duplicator only export current site's db tables.

### ISSUE THREAD

**Issue by lordspace** [lifeinthegrid/duplicator#2]
RE https://twitter.com/lifeinthegrid/status/464136128266657792

``` php
$db = new PDO("mysql:host=$host;charset=utf8", $user, $pass, array(
    PDO::ATTR_EMULATE_PREPARES => false,
    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
));

$sth = $db->query("USE " . $db_name); // select the db
$sth = $db->query("SHOW TABLES LIKE '$prefix%';");
$table_names = $sth->fetchAll(PDO::FETCH_COLUMN);

if (!empty($table_names)) {
    $cmd .= ' ' . join(' ', $table_names);
}`

$cmd is the regular mysqldump
```

**Comment by lordspace** [comment]
Cory, I almost submitted the same feature request :smile: ...
Ok. It would really helpful to have a link that using JavaScript to select only current site's db. tables.
That would save us at least 11-12 clicks which is a lot.

**Comment by lifeinthegrid** [comment]
Hey Svetoslav,

 

Maybe I don’t fully understand the requirement.   When you check any one of the database tables in the installer and create the package it should retain those tables that were checked for the next time you create the package.  Are you needing to change these up each time?   

 

The Pro version has custom Templates which allow you to save off any custom filter you want to re-use over and over, I’m not sure is that what you’re looking for…

 

Feel free to contact me directly if you want…

 

Cheers~

**Comment by lordspace** [comment]
Cory, what I meant is that duplicator should only select tables that belong to the current site and not the whole db. To me it makes sense to be the default.
Also if there's a way to change the prefix within the sql file this won't require an empty db all the time.

**Comment by lifeinthegrid** [comment]
Hey Svetoslav, 

Thanks for the feedback!  We have plans to have a "Core WordPress Site only" in the future it will be integrated into the pro version first then eventually trickle down to the free version.

Cheers~

**Comment by lordspace** [comment]
Cool.
