### ISSUE TITLE
Images paths added with Elementor are not updated

### ISSUE THREAD

**Issue by gfdesign** [lifeinthegrid/duplicator#22]
Dear support
I am a frequent user of your plugin but it doesn't work well when I have to migrate a site with pages created with Elementor page builder plugin. Elementor has two options to save image paths: in database or in .css files. They recommend do it in .css files due to perfomance issues, however Duplicator ignores these .css files when changes the image paths and we have to do it manually.
Would you mind take a look in this issue when you have a chance?
Duplicator and Elementor are in my top 10 plugins and they should get along each other :)
Let me know if I can help with more information
Best regards

**Comment by lifeinthegrid** [comment]
Hi gfdesign,

Sorry for the delay somehow it got overlooked.  If your still having issues with this go ahead and submit a support ticket here:  https://snapcreek.com/ticket and we can take a closer look.
