### ISSUE TITLE
Internal server error caused by not fixing .htaccess

### ISSUE THREAD

**Issue by lordspace** [lifeinthegrid/duplicator#25]
I run a SaaS app that provides test WP sites for people.
Somebody packaged their dev site which was installed in a folder e.g. /localhost/some-client/

When the user imported the site on my platform (at root level /) everything went well all pages except /  were causing internal server error 500.

Corrected .htaccess

```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>
```

Unreplaced RewriteBase and the RewriteRule in the .htaccess were causing the error.

```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /some-client/
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /some-client/index.php [L]
</IfModule>

```

**Comment by lifeinthegrid** [comment]
Thanks for the feedback!  Right now we don't do any mods to the .htaccess because there are so many combinations we just reset it and only apply what WordPress core sets.  This way we keep it simple...

**Comment by lordspace** [comment]
You're welcome Cory. 
Maybe your code resets it without checking the location where the new WP is installed in.
I will make some fixes on my end to correct any paths as quick(er) solution.

Slavi

**Comment by lifeinthegrid** [comment]
closing issue.   best approach for this will be to enable the option on step 1 of the installer to not touch .htaccess file.
